<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1754" started-at="2019-07-11T21:56:29Z" finished-at="2019-07-11T21:56:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1754" started-at="2019-07-11T21:56:29Z" finished-at="2019-07-11T21:56:31Z">
      <class name="daotest.DishDAOTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:daotest.DishDAOTest@46d56d67]" name="setUp" is-config="true" duration-ms="4033" started-at="2019-07-11T21:56:25Z" finished-at="2019-07-11T21:56:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="selectDishById()[pri:1, instance:daotest.DishDAOTest@46d56d67]" name="selectDishById" duration-ms="69" started-at="2019-07-11T21:56:29Z" finished-at="2019-07-11T21:56:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectDishById -->
        <test-method status="PASS" signature="insertDish()[pri:2, instance:daotest.DishDAOTest@46d56d67]" name="insertDish" duration-ms="321" started-at="2019-07-11T21:56:29Z" finished-at="2019-07-11T21:56:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertDish -->
        <test-method status="PASS" signature="updateDish()[pri:3, instance:daotest.DishDAOTest@46d56d67]" name="updateDish" duration-ms="570" started-at="2019-07-11T21:56:30Z" finished-at="2019-07-11T21:56:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateDish -->
        <test-method status="FAIL" signature="selectAllDishes()[pri:4, instance:daotest.DishDAOTest@46d56d67]" name="selectAllDishes" duration-ms="383" started-at="2019-07-11T21:56:30Z" finished-at="2019-07-11T21:56:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[lists don't have the same size expected [4] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: lists don't have the same size expected [4] but found [2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:796)
at daotest.DishDAOTest.selectAllDishes(DishDAOTest.java:94)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectAllDishes -->
        <test-method status="FAIL" signature="selectDishesByTags()[pri:5, instance:daotest.DishDAOTest@46d56d67]" name="selectDishesByTags" duration-ms="177" started-at="2019-07-11T21:56:31Z" finished-at="2019-07-11T21:56:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[lists don't have the same size expected [0] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: lists don't have the same size expected [0] but found [1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:796)
at daotest.DishDAOTest.selectDishesByTags(DishDAOTest.java:107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectDishesByTags -->
        <test-method status="PASS" signature="deleteDishById()[pri:6, instance:daotest.DishDAOTest@46d56d67]" name="deleteDishById" duration-ms="210" started-at="2019-07-11T21:56:31Z" finished-at="2019-07-11T21:56:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteDishById -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:daotest.DishDAOTest@46d56d67]" name="tearDown" is-config="true" duration-ms="201" started-at="2019-07-11T21:56:31Z" finished-at="2019-07-11T21:56:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- daotest.DishDAOTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
